title: Testing Distributed Systems
description: Curated list of materials on testing distributed systems
author: Andrey Satarin 
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
